package com.napt.spring.entity;

// Generated Apr 6, 2017 9:39:57 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmployeeStoreMap generated by hbm2java
 */
@Entity
@Table(name = "employee_store_map", catalog = "money_interest_manager")
public class EmployeeStoreMap implements java.io.Serializable {

	private Integer id;
	private int employeeId;
	private int storeId;

	public EmployeeStoreMap() {
	}

	public EmployeeStoreMap(int employeeId, int storeId) {
		this.employeeId = employeeId;
		this.storeId = storeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Employee_Id", nullable = false)
	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "Store_Id", nullable = false)
	public int getStoreId() {
		return this.storeId;
	}

	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}

}
