package com.napt.spring.entity;

// Generated Apr 6, 2017 9:39:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Merchandise generated by hbm2java
 */
@Entity
@Table(name = "merchandise", catalog = "money_interest_manager")
public class Merchandise implements java.io.Serializable {

	private Integer id;
	private String name;
	private String code;
	private long money;
	private int areaId;
	private boolean status;
	private int interestPeriodId;
	private Date overDate;

	public Merchandise() {
	}

	public Merchandise(String name, String code, long money, int areaId,
			boolean status, int interestPeriodId, Date overDate) {
		this.name = name;
		this.code = code;
		this.money = money;
		this.areaId = areaId;
		this.status = status;
		this.interestPeriodId = interestPeriodId;
		this.overDate = overDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "Money", nullable = false, precision = 10, scale = 0)
	public long getMoney() {
		return this.money;
	}

	public void setMoney(long money) {
		this.money = money;
	}

	@Column(name = "Area_Id", nullable = false)
	public int getAreaId() {
		return this.areaId;
	}

	public void setAreaId(int areaId) {
		this.areaId = areaId;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "Interest_Period_Id", nullable = false)
	public int getInterestPeriodId() {
		return this.interestPeriodId;
	}

	public void setInterestPeriodId(int interestPeriodId) {
		this.interestPeriodId = interestPeriodId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OverDate", nullable = false, length = 10)
	public Date getOverDate() {
		return this.overDate;
	}

	public void setOverDate(Date overDate) {
		this.overDate = overDate;
	}

}
