package com.napt.spring.entity;

// Generated Apr 6, 2017 9:39:57 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RevenueManagement generated by hbm2java
 */
@Entity
@Table(name = "revenue_management", catalog = "money_interest_manager")
public class RevenueManagement implements java.io.Serializable {

	private Integer id;
	private int userId;
	private String type;
	private String investmentType;

	public RevenueManagement() {
	}

	public RevenueManagement(int userId, String type, String investmentType) {
		this.userId = userId;
		this.type = type;
		this.investmentType = investmentType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "User_Id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "Type", nullable = false, length = 30)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "Investment_Type", nullable = false, length = 30)
	public String getInvestmentType() {
		return this.investmentType;
	}

	public void setInvestmentType(String investmentType) {
		this.investmentType = investmentType;
	}

}
