package com.napt.spring.entity;

// Generated Apr 6, 2017 9:39:57 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Store generated by hbm2java
 */
@Entity
@Table(name = "store", catalog = "money_interest_manager")
public class Store implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address;
	private String phone;
	private String investment;
	private boolean status;
	private BigDecimal cashFund;
	private String personRepresent;
	private Date createdDate;

	public Store() {
	}

	public Store(String name, String address, String phone, String investment,
			boolean status, BigDecimal cashFund, String personRepresent,
			Date createdDate) {
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.investment = investment;
		this.status = status;
		this.cashFund = cashFund;
		this.personRepresent = personRepresent;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Address", nullable = false, length = 150)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Phone", nullable = false, length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Investment", nullable = false, length = 100)
	public String getInvestment() {
		return this.investment;
	}

	public void setInvestment(String investment) {
		this.investment = investment;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "CashFund", nullable = false, precision = 20, scale = 0)
	public BigDecimal getCashFund() {
		return this.cashFund;
	}

	public void setCashFund(BigDecimal cashFund) {
		this.cashFund = cashFund;
	}

	@Column(name = "person_represent", nullable = false, length = 30)
	public String getPersonRepresent() {
		return this.personRepresent;
	}

	public void setPersonRepresent(String personRepresent) {
		this.personRepresent = personRepresent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", nullable = false, length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
