package com.napt.spring.entity;

// Generated Apr 6, 2017 9:39:57 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserTokenMap generated by hbm2java
 */
@Entity
@Table(name = "user_token_map", catalog = "money_interest_manager")
public class UserTokenMap implements java.io.Serializable {

	private Integer id;
	private int userId;
	private String jwtToken;

	public UserTokenMap() {
	}

	public UserTokenMap(int userId, String jwtToken) {
		this.userId = userId;
		this.jwtToken = jwtToken;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userId", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "jwtToken", nullable = false, length = 200)
	public String getJwtToken() {
		return this.jwtToken;
	}

	public void setJwtToken(String jwtToken) {
		this.jwtToken = jwtToken;
	}

}
