package com.napt.spring.entity;

// Generated Apr 6, 2017 9:39:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserContractMap generated by hbm2java
 */
@Entity
@Table(name = "user_contract_map", catalog = "money_interest_manager")
public class UserContractMap implements java.io.Serializable {

	private Integer id;
	private Date fromDate;
	private Date toDate;
	private int contractStatusId;
	private long moneyGiveToGuest;
	private int ratioId;
	private long moneyPaid;
	private long oldDebtMoney;
	private Date mustPay;
	private int borrowDays;
	private Date dateMustPay;
	private boolean contractState;

	public UserContractMap() {
	}

	public UserContractMap(Date fromDate, Date toDate, int contractStatusId,
			long moneyGiveToGuest, int ratioId, long moneyPaid,
			long oldDebtMoney, Date mustPay, int borrowDays, Date dateMustPay,
			boolean contractState) {
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.contractStatusId = contractStatusId;
		this.moneyGiveToGuest = moneyGiveToGuest;
		this.ratioId = ratioId;
		this.moneyPaid = moneyPaid;
		this.oldDebtMoney = oldDebtMoney;
		this.mustPay = mustPay;
		this.borrowDays = borrowDays;
		this.dateMustPay = dateMustPay;
		this.contractState = contractState;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FromDate", nullable = false, length = 10)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ToDate", nullable = false, length = 10)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	@Column(name = "Contract_Status_Id", nullable = false)
	public int getContractStatusId() {
		return this.contractStatusId;
	}

	public void setContractStatusId(int contractStatusId) {
		this.contractStatusId = contractStatusId;
	}

	@Column(name = "Money_Give_To_Guest", nullable = false, precision = 10, scale = 0)
	public long getMoneyGiveToGuest() {
		return this.moneyGiveToGuest;
	}

	public void setMoneyGiveToGuest(long moneyGiveToGuest) {
		this.moneyGiveToGuest = moneyGiveToGuest;
	}

	@Column(name = "Ratio_Id", nullable = false)
	public int getRatioId() {
		return this.ratioId;
	}

	public void setRatioId(int ratioId) {
		this.ratioId = ratioId;
	}

	@Column(name = "Money_Paid", nullable = false, precision = 10, scale = 0)
	public long getMoneyPaid() {
		return this.moneyPaid;
	}

	public void setMoneyPaid(long moneyPaid) {
		this.moneyPaid = moneyPaid;
	}

	@Column(name = "Old_Debt_Money", nullable = false, precision = 10, scale = 0)
	public long getOldDebtMoney() {
		return this.oldDebtMoney;
	}

	public void setOldDebtMoney(long oldDebtMoney) {
		this.oldDebtMoney = oldDebtMoney;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Must_Pay", nullable = false, length = 10)
	public Date getMustPay() {
		return this.mustPay;
	}

	public void setMustPay(Date mustPay) {
		this.mustPay = mustPay;
	}

	@Column(name = "Borrow_Days", nullable = false)
	public int getBorrowDays() {
		return this.borrowDays;
	}

	public void setBorrowDays(int borrowDays) {
		this.borrowDays = borrowDays;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_Must_Pay", nullable = false, length = 10)
	public Date getDateMustPay() {
		return this.dateMustPay;
	}

	public void setDateMustPay(Date dateMustPay) {
		this.dateMustPay = dateMustPay;
	}

	@Column(name = "Contract_State", nullable = false)
	public boolean isContractState() {
		return this.contractState;
	}

	public void setContractState(boolean contractState) {
		this.contractState = contractState;
	}

}
