package com.napt.spring.entity;

// Generated Apr 6, 2017 10:54:21 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserAuthoritiesMap generated by hbm2java
 */
@Entity
@Table(name = "user_authorities_map", catalog = "money_interest_manager")
public class UserAuthoritiesMap implements java.io.Serializable {

	private Integer id;
	private int userId;
	private String authorities;

	public UserAuthoritiesMap() {
	}

	public UserAuthoritiesMap(int userId, String authorities) {
		this.userId = userId;
		this.authorities = authorities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "authorities", nullable = false, length = 50)
	public String getAuthorities() {
		return this.authorities;
	}

	public void setAuthorities(String authorities) {
		this.authorities = authorities;
	}

}
